---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 16.14.1

inputs:
  - name: dp-maps-js

outputs:
  - name: build
  - name: package


run:
  path: dp-maps-js/ci/scripts/build.sh
