---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 17-stretch

inputs:
  - name: dp-maps-js

outputs:
  - name: dp-maps-js

run:
  path: dp-maps-js/ci/scripts/build.sh
